export const CREATE_TODO = 'CREATE_TODO';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_ERROR = 'CREATE_TODO_ERROR';

export const GET_TODO_LIST = 'GET_TODO_LIST';
export const GET_TODO_LIST_SUCCESS = 'GET_TODO_LIST_SUCCESS';
export const GET_TODO_LIST_ERROR = 'GET_TODO_LIST_ERROR';

export const IS_DONE_START = 'IS_DONE_START';
export const IS_DONE_SUCCESS = 'IS_DONE_SUCCESS';
export const IS_DONE_ERROR = 'IS_DONE_ERROR';
